version: '3.7'

services:
  pgadmin:
    container_name: pgadmin
    depends_on:
      - postgres
    env_file: .env
    image: dpage/pgadmin4
    links:
      - postgres
    ports:
      - '5050:80'
    restart: unless-stopped
    volumes:
      - pgadmin:/root/.pgadmin

  postgres:
    container_name: postgres
    env_file: .env
    image: postgres
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: {}
  pgadmin: {}
