export enum TYPES_ENUM {
  // Connections
  DATABASE_CONNECTION = 'DATABASE_CONNECTION',

  // REPOSITORIES
  TEST_REPOSITORY = 'TEST_REPOSITORY',

  // Services
  TEST_SERVICE = 'TEST_SERVICE',

  // Utils
  LOGGER = 'LOGGER'
}
