export enum TYPES_ENUM {
  // APP
  APP = 'APP',

  // Database
  DATABASE_CONNECTION = 'DATABASE_CONNECTION',
  ENTITY_MANAGER = 'ENTITY_MANAGER',

  // Services
  TEST_SERVICE = 'TEST_SERVICE',

  // Utils
  LOGGER = 'LOGGER'
}
